for s in attend deliberate consolidate skillify; do
  f="$ROOT/skills/$s/SKILL.md"
  [ -s "$f" ]; assert_ok $? "core skill exists: $s"
  assert_eq "$(sed -n 's/^name: //p' "$f" | head -1)" "$s" "frontmatter name matches: $s"
  [ -n "$(sed -n 's/^description: //p' "$f" | head -1)" ]; assert_ok $? "description non-empty: $s"
done
grep -q "evidence_plan" "$ROOT/skills/attend/SKILL.md" 2>/dev/null && grep -q "roadmap_ref" "$ROOT/skills/attend/SKILL.md" 2>/dev/null
assert_ok $? "attend carries full frame schema"
grep -qi "cascade" "$ROOT/skills/deliberate/SKILL.md" 2>/dev/null && grep -qi "conductor" "$ROOT/skills/deliberate/SKILL.md" 2>/dev/null
assert_ok $? "deliberate contains the cascade + conductor"
grep -qi "Roadmap gate" "$ROOT/skills/deliberate/SKILL.md" 2>/dev/null && grep -qi "blocks for the human" "$ROOT/skills/deliberate/SKILL.md" 2>/dev/null
assert_ok $? "deliberate carries the human gates"
ok=0
for t in claim preference decision goal policy; do grep -q "$t" "$ROOT/skills/consolidate/SKILL.md" 2>/dev/null || ok=1; done
grep -q "regen-index" "$ROOT/skills/consolidate/SKILL.md" 2>/dev/null || ok=1
assert_eq "$ok" "0" "consolidate covers all record types + regen-index"
grep -qi "idempotent" "$ROOT/skills/skillify/SKILL.md" 2>/dev/null && grep -qi "dry-run" "$ROOT/skills/skillify/SKILL.md" 2>/dev/null
assert_ok $? "skillify covers idempotent bootstrap + dry-run"
grep -qi "lifetime" "$ROOT/skills/deliberate/SKILL.md" 2>/dev/null && grep -q "plans/" "$ROOT/skills/deliberate/SKILL.md" 2>/dev/null
assert_ok $? "deliberate carries the plan-persistence lifetime rule"
grep -qi "resume the original builder" "$ROOT/skills/deliberate/SKILL.md" 2>/dev/null && grep -qi "pre-fix snapshot" "$ROOT/skills/deliberate/SKILL.md" 2>/dev/null
assert_ok $? "deliberate codifies D011 fix-round continuation"
grep -qi "retrospect" "$ROOT/skills/consolidate/SKILL.md" 2>/dev/null
assert_ok $? "consolidate runs the session retrospective"
for s in spec plan; do
  f="$ROOT/skills/$s/SKILL.md"
  [ -s "$f" ]; assert_ok $? "document skill exists: $s"
  assert_eq "$(sed -n 's/^name: //p' "$f" | head -1)" "$s" "frontmatter name matches: $s"
done
grep -q "docs/specs/" "$ROOT/skills/spec/SKILL.md" 2>/dev/null && grep -qi "pre-registered\|pre-registration" "$ROOT/skills/spec/SKILL.md" 2>/dev/null && grep -qi "success criteria" "$ROOT/skills/spec/SKILL.md" 2>/dev/null
assert_ok $? "spec skill: filing path + experiment pre-registration + success criteria"
grep -q "docs/plans/" "$ROOT/skills/plan/SKILL.md" 2>/dev/null && grep -qi "no placeholder" "$ROOT/skills/plan/SKILL.md" 2>/dev/null && grep -qi "cascade plan" "$ROOT/skills/plan/SKILL.md" 2>/dev/null
assert_ok $? "plan skill: filing path + no-placeholders + cascade plan format"
grep -q "plan skill" "$ROOT/skills/deliberate/SKILL.md" 2>/dev/null
assert_ok $? "deliberate references the plan skill"
grep -q "story_ref" "$ROOT/skills/attend/SKILL.md" 2>/dev/null && grep -qi "HIGH-LEVEL-STORIES" "$ROOT/skills/attend/SKILL.md" 2>/dev/null
assert_ok $? "attend frames carry story_ref against the value standard"
f="$ROOT/skills/direction/SKILL.md"
[ -s "$f" ]; assert_ok $? "direction skill exists"
assert_eq "$(sed -n 's/^name: //p' "$f" | head -1)" "direction" "direction skill name matches"
grep -q "ROADMAP.md" "$f" && grep -q "HIGH-LEVEL-STORIES.md" "$f"; assert_ok $? "direction covers both organs"
grep -q "As a" "$f" && grep -qi "draft-for-ratification" "$f"; assert_ok $? "direction carries story shape + ratification rule"
grep -qi "visionary\|product-manager" "$f"; assert_ok $? "direction names its managing roles"
grep -q "direction skill" "$ROOT/roles/visionary.md" && grep -q "direction skill" "$ROOT/roles/product-manager.md" && grep -q "direction skill" "$ROOT/roles/requirements-analyst.md"
assert_ok $? "all three managing roles reference the direction skill"
grep -q "mkdir -m 700" "$ROOT/skills/consolidate/SKILL.md" && \
  grep -q "umask 077" "$ROOT/skills/consolidate/SKILL.md" && \
  awk '/mkdir -m 700/{a=NR} /umask 077/{if(!b)b=NR} /trust --global/{if(!c)c=NR} END{exit !(a && b && c && a<=b && b<=c)}' "$ROOT/skills/consolidate/SKILL.md"
assert_ok $? "consolidate creation flow in load-bearing order (mkdir -> umask cp -> trust --global)"
awk '/project store as a normal record/{a=NR} /scope-deferred/{if(!b)b=NR} END{exit !(a && b && a<b)}' "$ROOT/skills/consolidate/SKILL.md"
assert_ok $? "deferral is record-then-event, in that order"
grep -qi "routing classes" "$ROOT/skills/consolidate/SKILL.md" && grep -qi "scoped-exception" "$ROOT/skills/consolidate/SKILL.md"
assert_ok $? "consolidate carries routing classes + cross-tier precedence"
grep -q "/goal" "$ROOT/skills/attend/SKILL.md"
assert_ok $? "attend mirrors an active /goal into the frame"
grep -q "session-append" "$ROOT/skills/attend/SKILL.md" && grep -qi "extend" "$ROOT/skills/attend/SKILL.md"
assert_ok $? "attend: frames via session-append + extension affordance"
grep -qi "instruction.*ratif\|ratif.*instruction" "$ROOT/skills/consolidate/SKILL.md"
assert_ok $? "consolidate: instruction-is-ratification documented"
f="$ROOT/skills/git/SKILL.md"
[ -s "$f" ]; assert_ok $? "git skill exists"
assert_eq "$(sed -n 's/^name: //p' "$f" | head -1)" "git" "git skill name matches"
grep -qi "worktree" "$f" && grep -qi "never implement on main" "$f" && grep -qi "Co-Authored-By" "$f"
assert_ok $? "git skill covers worktrees, main protection, trailers"
grep -qi "stage explicitly" "$f" && grep -qi "integration is the human" "$f" && grep -qi "re-trust" "$f"
assert_ok $? "git skill covers explicit staging, human merge decision, worktree trust"
grep -qi "git skill" "$ROOT/commands/implement.md"
assert_ok $? "implement cites the git skill at commit time"
grep -qi "git skill" "$ROOT/skills/deliberate/SKILL.md"
assert_ok $? "deliberate cites the git skill for execution"
grep -qi "backups/" "$ROOT/skills/skillify/SKILL.md"
assert_ok $? "#6 skillify names the backup home"
grep -q "append-todo" "$ROOT/skills/consolidate/SKILL.md" && grep -q "append-lesson" "$ROOT/skills/consolidate/SKILL.md"
assert_ok $? "#2 quick-reference includes todo/lesson helpers"
f="$ROOT/skills/feedback/SKILL.md"
[ -s "$f" ]; assert_ok $? "feedback skill exists"
assert_eq "$(sed -n 's/^name: //p' "$f" | head -1)" "feedback" "feedback skill name matches"
grep -qi "field report" "$f" && grep -qi "Adegbolahan/anoti" "$f"
assert_ok $? "feedback: field-report format targeting the anoti repo"
grep -qi "dedup" "$f" && grep -qi "gh issue list" "$f"
assert_ok $? "feedback: dedup against existing issues before proposing"
grep -qi "outward-facing" "$f" && grep -qi "never file without" "$f"
assert_ok $? "feedback: issue creation human-gated, never automatic"
grep -q 'mkdir -p "<state-dir>/feedback"' "$f" && grep -q "feedback/YYYY-MM-DD-<slug>.md" "$f"
assert_ok $? "feedback: queue dir created and exact draft path named"
grep -q "pending.md" "$f" && grep -qi "queued feedback draft" "$f"
assert_ok $? "feedback: queued drafts ride the pending.md surface"
grep -qi "the feedback skill" "$ROOT/skills/policy-retrospect/SKILL.md"
assert_ok $? "retrospect routes anoti friction via the feedback skill"
grep -qi "feedback" "$ROOT/docs/SKILL-MAP.md"
assert_ok $? "SKILL-MAP lists the feedback skill"
grep -q "session-consume" "$ROOT/skills/consolidate/SKILL.md"
assert_ok $? "#9 consolidate names the mechanical consume step"
grep -qi "mark candidates consumed" "$ROOT/skills/consolidate/SKILL.md"
assert_ok $? "#9 the numbered procedure itself instructs the consume call"
grep -qi "applied" "$ROOT/skills/consolidate/SKILL.md"
assert_ok $? "#9 consolidate collects only unapplied candidates"
f="$ROOT/skills/demo/SKILL.md"
[ -s "$f" ]; assert_ok $? "demo skill exists"
assert_eq "$(sed -n 's/^name: //p' "$f" | head -1)" "demo" "demo skill name matches"
grep -qi "when to use what" "$f"
assert_ok $? "demo: routing promise in the body"
for w in attend deliberate consolidate feedback skillify "review-work" recall audit direction; do grep -q "$w" "$f" || { echo "demo missing route: $w" >&2; false; break; }; done
assert_ok $? "demo: routes cover the cycle and commands"
grep -q "ANOTI_DIR" "$f" && grep -qi "scratch\|temp" "$f"
assert_ok $? "demo: hands-on tour runs against scratch state only"
grep -qi "outsource" "$f"
assert_ok $? "demo: names the slogan-level why"
grep -qi "demo skill" "$ROOT/commands/new.md"
assert_ok $? "demo skill reachable from /anoti:new"
grep -q "demo skill" "$ROOT/scripts/retrieve"
assert_ok $? "SessionStart digest surfaces the demo-skill orientation line"
grep -qi "anoti-dir" "$ROOT/skills/demo/SKILL.md"
assert_ok $? "demo tour verifies the sandbox before writing (anoti-dir check)"
grep -qi "not an adversarial" "$ROOT/skills/demo/SKILL.md" || ! grep -qi "review-work.*adversarial" "$ROOT/skills/demo/SKILL.md"
assert_ok $? "demo does not mislabel review-work as adversarial"
grep -qi "demo" "$ROOT/docs/SKILL-MAP.md"
assert_ok $? "SKILL-MAP lists the demo skill"
grep -qi "case-insensitive" "$ROOT/skills/skillify/SKILL.md"
assert_ok $? "#11 skillify detects case-insensitive organ collisions"
grep -q "set-ratification" "$ROOT/skills/consolidate/SKILL.md" && grep -q "set-status" "$ROOT/skills/consolidate/SKILL.md"
assert_ok $? "#10 consolidate quick-reference carries the field-writing helpers"
! grep -q 'Status/ratification changes:.*append-event' "$ROOT/skills/consolidate/SKILL.md"
assert_ok $? "#10 no doc still routes field changes through append-event"
grep -q "LESSONS-LEARNT" "$ROOT/skills/attend/SKILL.md"
assert_ok $? "attend topical retrieval greps the lessons organ"
grep -q "complete-todo" "$ROOT/skills/consolidate/SKILL.md"
assert_ok $? "#12 consolidate quick-reference carries complete-todo"
grep -qi "graduat" "$ROOT/skills/consolidate/SKILL.md" && grep -qi "global" "$ROOT/skills/consolidate/SKILL.md"
assert_ok $? "gap 5: consolidate routes cross-project lessons toward the global tier"
grep -q "Execution routing" "$ROOT/skills/spec/SKILL.md"
assert_ok $? "spec standard requires execution routing (roles/skills named)"
grep -qi "every task names its role" "$ROOT/skills/plan/SKILL.md"
assert_ok $? "plan standard requires an owner-role per task"
grep -qi "misfiled memory is worse than no memory" "$ROOT/skills/consolidate/SKILL.md" && ! grep -q "Project-scoped goes$" "$ROOT/skills/consolidate/SKILL.md"
assert_ok $? "scope-routing prose is whole (garble regression pin)"
grep -qi "how to choose" "$ROOT/skills/spec/SKILL.md" && grep -q "SKILL-MAP" "$ROOT/skills/spec/SKILL.md"
assert_ok $? "spec routing says HOW to choose (roles register + SKILL-MAP)"
awk '/Experiment spec/,/## Rules/' "$ROOT/skills/spec/SKILL.md" | grep -qi "routing"
assert_ok $? "experiment specs carry execution routing too"
grep -qi "plan skill" "$ROOT/skills/spec/SKILL.md"
assert_ok $? "spec names its handoff: the plan skill picks up the routing"
grep -q "resolve-question" "$ROOT/skills/consolidate/SKILL.md"
assert_ok $? "#14 consolidate quick-reference carries resolve-question"
grep -qi "plugin root" "$ROOT/skills/spec/SKILL.md"
assert_ok $? "spec routing resolves roles/SKILL-MAP from the plugin root (governed projects have no local copy)"
grep -qi "spec_dir\|organ homes" "$ROOT/skills/skillify/SKILL.md"
assert_ok $? "#16 skillify skips scaffolding adopted organ homes and records the mapping"
grep -q "spec_dir" "$ROOT/skills/spec/SKILL.md"
assert_ok $? "#16 spec skill files to the recorded organ home, not a hardcoded path"
grep -q "plan_dir" "$ROOT/skills/plan/SKILL.md"
assert_ok $? "#16 plan skill files to the recorded organ home"
grep -qi "exactly what it created" "$ROOT/skills/skillify/SKILL.md"
assert_ok $? "#16 the bootstrap record states exactly what was created"
grep -q "todos_path" "$ROOT/skills/skillify/SKILL.md" && grep -q "roadmap_path" "$ROOT/skills/skillify/SKILL.md"
assert_ok $? "#18 skillify names the organ-path keys for brownfield adoption"
grep -qi "symlink" "$ROOT/skills/skillify/SKILL.md"
assert_ok $? "#18 skillify offers the symlink alternative (human-ratified)"
grep -qi "canonical basename\|episode gate keys on" "$ROOT/skills/skillify/SKILL.md"
assert_ok $? "#18 the gate limitation of renamed organs is stated, not silent"

# --- jit-recall spec §4.6: consolidate gains step 2b, the encoding-time question ---
# The markdown formatter hook reflows a non-standard ordinal ("2b.") into
# an indented continuation of item 2, not column 0 -- same established
# reflow already visible on the pre-existing "8b." step
# (skills/consolidate/SKILL.md:120). Anchored on content, tolerant of
# leading whitespace, instead of requiring an unreflowed "^2b." start.
grep -qE "2b\. \*\*Encoding-time cue question" "$ROOT/skills/consolidate/SKILL.md"
assert_ok $? "consolidate gains step 2b"
grep -q "what would you have needed to" "$ROOT/skills/consolidate/SKILL.md"
assert_ok $? "step 2b carries the encoding-time cue question"
grep -q "append-trigger" "$ROOT/skills/consolidate/SKILL.md"
assert_ok $? "step 2b names the append-trigger helper"
awk '/^2\. \*\*Type every candidate/{a=NR} /2b\. \*\*Encoding-time cue question/{b=NR} /^3\. \*\*Citations/{c=NR} END{exit !(a && b && c && a<b && b<c)}' "$ROOT/skills/consolidate/SKILL.md"
assert_ok $? "step 2b sits between step 2 and step 3, in order"
