h="$ROOT/hooks/hooks.json"
[ -f "$h" ]; assert_ok $? "hooks.json exists"
jq -e '.hooks | has("SessionStart") and has("UserPromptSubmit") and has("PreToolUse") and has("PreCompact") and has("Stop") and has("SessionEnd") and has("PostToolUse") and has("PostToolUseFailure")' "$h" >/dev/null 2>&1
assert_ok $? "all eight events wired"
assert_eq "$(jq -r '.hooks.SessionStart[0].hooks[0].timeout' "$h")" "10" "retrieve timeout 10s"
assert_eq "$(jq -r '.hooks.PreToolUse[0].matcher' "$h")" "Bash|Write|Edit|NotebookEdit" "inhibition matcher scoped"
jq -e '.hooks | has("PostToolUse") and has("PostToolUseFailure")' "$h" >/dev/null 2>&1
assert_ok $? "PostToolUse and PostToolUseFailure both wired"
assert_eq "$(jq -r '.hooks.PostToolUse[0].matcher' "$h")" "Bash|Write|Edit|NotebookEdit" "presence matcher scoped (PostToolUse)"
assert_eq "$(jq -r '.hooks.PostToolUseFailure[0].matcher' "$h")" "Bash|Write|Edit|NotebookEdit" "presence matcher scoped (PostToolUseFailure)"
assert_eq "$(jq -r '.hooks.PostToolUse[0].hooks[0].command' "$h")" "\${CLAUDE_PLUGIN_ROOT}/scripts/presence" "PostToolUse points at presence"
assert_eq "$(jq -r '.hooks.PostToolUseFailure[0].hooks[0].command' "$h")" "\${CLAUDE_PLUGIN_ROOT}/scripts/presence" "PostToolUseFailure points at the SAME script"
assert_eq "$(jq -r '.hooks.PostToolUse[0].hooks[0].timeout' "$h")" "5" "presence timeout 5s (PostToolUse)"
assert_eq "$(jq -r '.hooks.PostToolUseFailure[0].hooks[0].timeout' "$h")" "5" "presence timeout 5s (PostToolUseFailure)"
# every referenced script exists and is executable (resolve ${CLAUDE_PLUGIN_ROOT} to repo root)
for cmd in $(jq -r '.. | .command? // empty' "$h"); do
  real="${cmd/\$\{CLAUDE_PLUGIN_ROOT\}/$ROOT}"
  [ -x "$real" ]; assert_ok $? "wired script exists+executable: $real"
done
n="$(printf '{"session_id":"w","prompt":"refactor the auth module and change the session policy"}' | "$ROOT/scripts/classify" | jq -r '.hookSpecificOutput.additionalContext' | wc -l | tr -d ' ')"
[ "$n" -le 10 ]; assert_ok $? "classifier injection is <= 10 lines (attention tax)"
printf '{"session_id":"w","prompt":"refactor the auth module and change the session policy"}' | "$ROOT/scripts/classify" | jq -r '.hookSpecificOutput.additionalContext' | grep -q "SLOW if"
assert_ok $? "classifier carries concrete slow criteria"
printf '{"session_id":"w","prompt":"refactor the auth module and change the session policy"}' | "$ROOT/scripts/classify" | jq -r '.hookSpecificOutput.additionalContext' | grep -qi "decisions"
assert_ok $? "classifier names decision-setting as slow"
grep -q "macos" "$ROOT/.github/workflows/ci.yml"
assert_ok $? "gap 3: CI exercises the case-insensitivity tests on macOS"
awk '/tests-macos:/,/^  lint:/' "$ROOT/.github/workflows/ci.yml" | grep -q "bash tests/run.sh"
assert_ok $? "gap 3: the macOS job actually runs the suite (non-vacuous)"
grep -q "needs: \[tests, tests-macos" "$ROOT/.github/workflows/ci.yml"
assert_ok $? "gap 3: tests-macos gates the release"
