g="$ROOT/GROUNDING.yaml"
"$ROOT/scripts/validate-workspace" "$g" >/dev/null 2>&1
assert_ok $? "project grounding validates as v3"
assert_eq "$(yq -r '.meta.schema_version' "$g")" "3" "grounding schema is v3"
n="$(yq -r '.records | length' "$g")"
[ "$n" -ge 4 ]; assert_ok $? "at least the four migrated records present"
st="$(yq -r '.records[] | select(.id=="D001") | .epistemic_status' "$g")"
case "$st" in speculative|probable|established) ok=0 ;; *) ok=1 ;; esac
assert_eq "$ok" "0" "D001 carries a valid epistemic status (history lives in events)"
echo "$(yq -r '[.records[] | select(.id=="D001") | .events[].action] | join(",")' "$g")" | grep -q "demoted"
assert_ok $? "D001 carries a demoted event"
n="$(yq -r '.records[] | select(.id=="D004") | .evidence | length' "$g")"
[ "$n" -ge 1 ]; assert_ok $? "D004 has at least one evidence entry"
assert_eq "$(yq -r '.open_questions[0].id' "$g")" "Q001" "Q001 preserved"
assert_eq "$(yq -r '.index | length' "$g")" "$(yq -r '.records | length' "$g")" "index row count matches records"
